name: Create a release draft

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: install hub
      run: apt install -y hub
    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: hub release --draft ${{ github.event.inputs.tag }}
